### PR TITLE
Added splash screens and updated info page 

### PR DESCRIPTION
**Pull request by Tusar6701**
# Story Title

[This is the Issue Title](https://github.com/username/repository-name/issues/1)

## Changes made

-   added splash screens
-   updated the info-page

## How does the solution address the problem

This PR will add to the appeal of the application 

## Linked issues

Resolves the issue of poor design of the info page. As there was nothing much to be done in the information page, the theme has been changed to match the theme of HacktoberFest 2020 as closely as possible, without distorting the display of the information as originally intended.

### CODE REVIEW

**Comment by IshanDhruv** [comment]
Please check your code formatting and try to remove any unused imports.

**Comment by Tusar6701** [comment]
I have done the needful

**Comment by IshanDhruv** [comment]
It would be better if you could keep only the first splash screen - the Hacktoberfest splash screen. Having more than 1 splash screen seems unnecessary, and increases the opening time.

**Comment by Tusar6701** [comment]
Okay sure...
I thought the opening looked cool with all those screens

**Comment by Tusar6701** [comment]
Removed the extra splash screens

**Pull request merged**
