### PR TITLE
Sending Fixes for issue #6

### LINKED ISSUE #6: Create design templates
**Please describe the feature you want this project to offer**
Create design templates for the users to choose  from
**Describe the solution you'd like**
Create a list of design templates that the users will be able to choose from while adding their own cards.
**Describe alternatives you've considered (Optional)**
**Additional context (Optional)**

### PR DESCRIPTION
**Pull request by Zafershah24**
# Story Title

[This is the Issue Title](https://github.com/username/repository-name/issues/1)

## Changes made

-   added Animations to the cards, made a toggle button to swap between cards
-   made rounded cards

## How does the solution address the problem

This PR will include newly designed cards that reacts on clicking on them

## Linked issues

Resolves #6

### CODE REVIEW

**Comment by IshanDhruv** [comment]
Could you rebase and create a PR.

**Comment by Zafershah24** [comment]
Can you Please checkout if you could merge now?
I branch is 3 commits ahead of master and 5 commits behind

**Comment by IshanDhruv** [comment]
Could you integrate it with the Github API which is on the master branch.

**Comment by Zafershah24** [comment]
OK.. I will look into it.

**Comment by Zafershah24** [comment]
Hey I integrated the Github API along with my Codes, you can merge in now.

**Comment by Zafershah24** [comment]
You can Merge my Pull Request, with your "master" branch now, and for the changes. Thank You

**Pull request merged**
