### PR TITLE
[Added]: repo search functionality

### PR DESCRIPTION
**Pull request by SuvamPrasd**
# Story Title

[Search repos on GitHub](https://github.com/IEEE-VIT/hacktoberfest-flutter/issues/1)

## Changes made

-   Now the user able to find the GitHub repository with the help of a label or a tag respectively by searching.
-   I have used an HTTP package to call the Github API, Spinkit package to add an animated loading indicator, url_launch package to open the repo URL in the web browser.

## How does the solution address the problem

This PR will definitely give the functionality to the user to find the particular repository in the Github using a tag or a label in the search bar. 

## Linked issues

Resolves #1

### CODE REVIEW

**Comment by SuvamPrasd** [comment]
@C-Harshul please review the codes

**Comment by IshanDhruv** [comment]
Hey! Could you use the contributors page UI that is currently on the master branch? It has implemented the open in browser functionality.

**Comment by SuvamPrasd** [comment]
@IshanDhruv okay, I will implement the existing UI design however talking about the open in browser functionality, it has been included in the code.

**Comment by IshanDhruv** [comment]
Are you sure the links to the contributors' profile page open in the browser? I tried opening them on both card sets but it did not open.

**Comment by SuvamPrasd** [comment]
I have worked on the repo search functionality, not the contribution page functionality.

**Comment by IshanDhruv** [comment]
Kindly check your formatting and code linting.

**Comment by SuvamPrasd** [comment]
please close this PR. I have made another PR #26 for this issue and all the issue is fixed. @C-Harshul @IshanDhruv

**Pull request closed without merging**
