### PR TITLE
[Added]: search repo functionality

### PR DESCRIPTION
**Pull request by SuvamPrasd**
# Story Title

[Search repos on GitHub](https://github.com/IEEE-VIT/hacktoberfest-flutter/issues/1)

## Changes made

-   Now the user able to find the GitHub repository with the help of a label or a tag respectively by searching.
-   I have used an HTTP package to call the Github API, Spinkit package to add an animated loading indicator, url_launch package to open the repo URL in the web browser.

## How does the solution address the problem

This PR will definitely give the functionality to the user to find the particular repository in the Github using a tag or a label in the search bar.

## Linked issues

Resolves #1

### CODE REVIEW

**Comment by IshanDhruv** [comment]
Scrolling is uncomfortable on the search page. Could you update the card design or use another card?
Also the loading animation occurs by default even when no term is being searched. Could you please fix that bug.

**Comment by SuvamPrasd** [comment]
@IshanDhruv previously, you told me to update the card UI with the existing contribution page UI design, and I did that. Now you again told me to update the card design.

**Comment by SuvamPrasd** [comment]
@IshanDhruv The scrolling problem has been fixed, and instead of loading animation, there will be an image when the user does not search. Regarding card UI, I think the card design looks good.

**Comment by SuvamPrasd** [comment]
@IshanDhruv There were some small bugs, so I have fixed the problems.

**Pull request merged**
